### ISSUE TITLE
Implement ZipPasswordUploaded and ZipPasswordMapped

### ISSUE THREAD

**Issue by robcadhacker** [icarus-consulting/Yaapii.ZIP#17]
### Expected Behavior

Password protected zip entries can be updated/added or mapped. ZipPasswordUploaded and ZipPasswordMapped are implemented

### Actual Behavior

It is not possible to update/add or map password protected zip entries

### Mention any other details that might be useful

Implement it analog to ZipPasswordExtracted. Is possibly obsolete with #10 (#11)

**Comment by jaanpeeter** [comment]
Is implemented by: new ZipUpdated( new ZipWithPassword(..))
