### ISSUE TITLE
The release breakes at uploading assets

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.ZIP#38]
### Expected Behavior

the upload of the assets works
### Actual Behavior

the upload is breaking, so we have comment it
### Mention any other details that might be useful

![grafik](https://user-images.githubusercontent.com/32898876/195099699-172ac58c-0dae-44f9-a546-55c0b8b193b4.png)

**Comment by jaanpeeter** [comment]
@icaOBU : please describe the issue in another way. I do not unterstand what the problem is.

**Comment by icaOBU** [comment]
If i remember correctly, there was an API Change by Cake/Git which breaks the uploading of the assets to GitHub in the buildscript. I don´t know if there is a solution or a workaround now. 

The workaround for us was to comment the breaking part in the Buildscript ```GitReleaseManagerAddAssets(...)``` which results that no zip files and nuget packages where uploaded into the github release
